name: Flow-CI

on: [push, pull_request]

env:
  BRANCH_NAME: noBranch
  NUGET_PACKAGE_ID: NuGetTestPackage_VasilyAK
  RELEASE_VERSION: '0.0.0'

jobs:
  Build_Flow:
    name: Build Flow
    runs-on: windows-latest 

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Update release version
      run: .\Utils\DefineBranch.ps1 -NuGetPackageId env.NUGET_PACKAGE_ID
      shell: powershell

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x

    - name: Restore NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore dependencies
      run: dotnet restore "NuGetTestPackage/NuGetTestPackage.sln"

    - name: Build
      run: dotnet build "NuGetTestPackage/NuGetTestPackage.sln" --no-restore

    - name: Test
      if: ${{ env.BRANCH_NAME == 'release' }}
      run: dotnet test "NuGetTestPackage/NuGetTestPackage.sln" --no-build --verbosity normal

  Push_NuGet_Package:
    name: Push NuGet package
    needs: Build_Flow
    if: ${{ $BRANCH_NAME == 'release' && $RELEASE_VERSION != '0.0.0'}}
    runs-on: windows-latest
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${RELEASE_VERSION} --no-build --output 

    - name: Push
      run: dotnet nuget push NuGet.Workflow.${RELEASE_VERSION}.nupkg --source https://www.nuget.org/ --api-key ${NU_GET_ENV}
      env:
        NU_GET_ENV: ${{ secrets.TEST_PACKAGE_API_KEY }}